services:
  jolt-transform-web:
    image: halversondm/jolt-transform-web:latest
    networks:
      - app-tier
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "9200:8081"
networks:
  app-tier:
    driver: bridge
volumes:
  postgres_data: {}