import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import BuildPage from '../components/BuildPage';

const renderPage = () =>
    render(
        <MemoryRouter>
            <BuildPage />
        </MemoryRouter>
    );

describe('BuildPage', () => {
    afterEach(() => {
        vi.restoreAllMocks();
    });

    it('renders the AI warning banner', () => {
        renderPage();
        expect(screen.getByRole('status')).toHaveTextContent(
            'The JOLT spec is generated by AI and may contain errors.'
        );
    });

    it('renders Input, Output, and Spec labels', () => {
        renderPage();
        expect(screen.getByText('Input')).toBeInTheDocument();
        expect(screen.getByText('Output')).toBeInTheDocument();
        expect(screen.getByText('Spec')).toBeInTheDocument();
    });

    it('renders the Build Spec button', () => {
        renderPage();
        expect(screen.getByRole('button', { name: /build spec/i })).toBeInTheDocument();
    });

    it('shows an error when input is invalid JSON', async () => {
        renderPage();
        const [inputArea] = screen.getAllByRole('textbox');
        fireEvent.change(inputArea, { target: { value: 'not-json' } });
        await userEvent.click(screen.getByRole('button', { name: /^build spec$/i }));
        expect(await screen.findByText('Input is not valid JSON')).toBeInTheDocument();
    });

    it('shows an error when output is invalid JSON', async () => {
        renderPage();
        const textareas = screen.getAllByRole('textbox');
        fireEvent.change(textareas[0], { target: { value: '{"key":"value"}' } });
        fireEvent.change(textareas[1], { target: { value: 'bad-output' } });
        await userEvent.click(screen.getByRole('button', { name: /^build spec$/i }));
        expect(await screen.findByText('Output is not valid JSON')).toBeInTheDocument();
    });

    it('displays the generated spec on successful API response', async () => {
        vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce({
            ok: true,
            json: async () => ({ spec: '[{"operation":"shift"}]' }),
        }));

        renderPage();
        const textareas = screen.getAllByRole('textbox');
        fireEvent.change(textareas[0], { target: { value: '{"a":1}' } });
        fireEvent.change(textareas[1], { target: { value: '{"b":2}' } });
        await userEvent.click(screen.getByRole('button', { name: /^build spec$/i }));

        await waitFor(() => {
            expect(textareas[2]).toHaveValue(
                JSON.stringify(JSON.parse('[{"operation":"shift"}]'), null, 2)
            );
        });
    });

    it('shows an error when the API returns a non-ok response', async () => {
        vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce({ ok: false }));

        renderPage();
        await userEvent.click(screen.getByRole('button', { name: /^build spec$/i }));

        expect(await screen.findByText('Transformation failed')).toBeInTheDocument();
    });

    it('shows an error on network failure', async () => {
        vi.stubGlobal('fetch', vi.fn().mockRejectedValueOnce(new Error('Network error')));

        renderPage();
        await userEvent.click(screen.getByRole('button', { name: /^build spec$/i }));

        expect(await screen.findByText('Network or server error')).toBeInTheDocument();
    });

    it('disables the button while loading', async () => {
        vi.stubGlobal('fetch', vi.fn(() => new Promise(() => {})));

        renderPage();
        const button = screen.getByRole('button', { name: /^build spec$/i });
        await userEvent.click(button);

        expect(screen.getByRole('button', { name: /building spec/i })).toBeDisabled();
    });
});
